name: Deploy to Cloudflare Pages

on:
  # push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DEPLOYMENT_ENVIRONMENT:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - preview
          - production
        default: "production"

env:
  # Variables
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
  CLOUDFLARE_KV_ID: ${{ vars.CLOUDFLARE_KV_ID }}
  CLOUDFLARE_KV_PREVIEW_ID: ${{ vars.CLOUDFLARE_KV_PREVIEW_ID }}
  CLOUDFLARE_D1_ID: ${{ vars.CLOUDFLARE_D1_ID }}
  CLOUDFLARE_D1_PREVIEW_ID: ${{ vars.CLOUDFLARE_D1_PREVIEW_ID }}
  # Secrets
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.DEPLOYMENT_ENVIRONMENT }}
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4
      - name: 🏗 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: 📦 Install dependencies
        run: npm ci
      - name: ⛑ Build
        run: npm run build
      - name: 🚀 Deploy to Cloudflare Pages [${{ inputs.DEPLOYMENT_ENVIRONMENT }}]
        run: npm run deploy
